kind: pipeline
name: docker

steps:
- name: npm_install
  image: node:18-alpine
  commands: 
    - cd $DRONE_REPO_NAME
    - npm install
- name: npm_build
  image: node:18-alpine
  commands:
    - cd $DRONE_REPO_NAME
    - echo $DRONE_REPO_NAME
    - npm run build
  # depends_on:
  #   - npm_install
- name: image_build
  image: drone/docker
  privileged: true
  environment:
    DOCKER_REGISTRY: my-registry
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
  - cd $DRONE_REPO_NAME
  - echo $DRONE_REPO_NAME
  - docker build -t wrpscore:latest -f ./Dockerfile . --build-arg DRONE_COMMIT=$DRONE_COMMIT
  # depends_on:
  #   - npm_build



    

