kind: pipeline
name: docker

volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock

steps:
  - name: npm_install
    image: node:18-alpine
    commands:
      - cd $DRONE_REPO_NAME
      - npm install
  - name: npm_build
    image: node:18-alpine
    commands:
      - cd $DRONE_REPO_NAME
      - echo $DRONE_REPO_NAME
      - npm run build
    depends_on:
      - npm_install
  - name: docker
    image: drone/docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    commands:
      - docker build -f Dockerfile -t test_image .
    depends_on:
      - npm_build
