kind: pipeline
name: docker

steps:
- name: npm_install
  image: node:18-alpine
  commands: 
    - cd $DRONE_REPO_NAME
    - npm install
- name: npm_build
  image: node:18-alpine
  commands:
    - cd $DRONE_REPO_NAME
    - echo $DRONE_REPO_NAME
    - npm run build
  depends_on:
    - npm_install
- name: docker  
  image: drone/docker
  privileged: true
  commands:
    - docker build -f Dockerfile -t test_image .
volumes:
    - name: dockersock
      path: /var/run/docker.sock

      

    

