kind: pipeline
type: kubernetes
name: ci_pipeline1

steps:
- name: clone_project
  image: docker/github-actions:v1
  commands:
    - git clone $DRONE_REMOTE_URL
    - cd $DRONE_REPO_NAME
    - git checkout $DRONE_COMMIT
- name: npm_install
  image: node:18-alpine
  commands: 
    - cd $DRONE_REPO_NAME/wrp_score
    - npm install
  depends_on:
    - clone_project
- name: build
  image: node:18-alpine
  commands:
    - cd $DRONE_REPO_NAME/wrp_score
    - npm build
  depends_on:
    - npm_install