kind: pipeline
name: docker

steps:
  # - name: npm_install
  #   image: node:18-alpine
  #   commands:
  #     - echo $DRONE_REPO_NAME
  #     - npm install
  # - name: npm_build
  #   image: node:18-alpine
  #   commands:
  #     - npm run build
  #   depends_on:
  #     - npm_install
  # - name: build_image
  #   image: drone/docker
  #   volumes:
  #     - name: docker-socket
  #       path: /var/run/docker.sock
  #   commands:
  #     - docker build -t wrp-score:latest .
  #   depends_on:
  #     - npm_build
  - name: publish_image
    image: meisterplan/jfrog-cli
    environment:
      ARTIFACTORY_URL:
        from_secret: ARTIFACTORY_URL
      ARTIFACTORY_USERNAME:
        from_secret: ARTIFACTORY_USERNAME
      ARTIFACTORY_PASSWORD:
        from_secret: ARTIFACTORY_PASSWORD
      ARTIFACTORY_REPO_KEY:
        from_secret: ARTIFACTORY_REPO_KEY
    commands:
      - jfrog rt login $ARTIFACTORY_URL --user $ARTIFACTORY_USERNAME --password $PASSWORD
      - jfrog rt docker-push wrp-score:latest $ARTIFACTORY_URL/$ARTIFACTORY_REPO_KEY
      - jfrog rt logout $ARTIFACTORY_URL
volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
