kind: pipeline
name: test

steps:
  - name: npm_install
    image: node:18-alpine
    commands:
      - echo $DRONE_REPO_NAME
      - npm install
  - name: npm_build
    image: node:18-alpine
    commands:
      - npm run build
    depends_on:
      - npm_install
trigger:
  branch:
    - main
  event:
    - push

---
kind: pipeline
name: deploy
steps:
  - name: npm_install
    image: node:18-alpine
    commands:
      - echo $DRONE_REPO_NAME
      - npm install
  - name: npm_build
    image: node:18-alpine
    commands:
      - npm run build
    depends_on:
      - npm_install
  - name: publish_and_deploy
    image: drone/docker
    volumes:
      - name: docker-socket
        path: /var/run/docker.sock
    environment:
      ARTIFACTORY_USERNAME:
        from_secret: ARTIFACTORY_USERNAME
      ARTIFACTORY_ACCESS_TOKEN:
        from_secret: ARTIFACTORY_ACCESS_TOKEN
      ARTIFACTORY_REPOSITORY:
        from_secret: ARTIFACTORY_REPOSITORY
    commands:
     - docker stop wrp-score
     - docker build -t wrp-score:latest .
     - docker start wrp-score
     
    #  Publish image
     - echo Tag:$TAG_VERSION
     - docker login -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_ACCESS_TOKEN $ARTIFACTORY_REPOSITORY
     - docker tag wrp-score $ARTIFACTORY_REPOSITORY/goodies-docker/wrp-score:v_$TAG_VERSION
     - docker push $ARTIFACTORY_REPOSITORY/goodies-docker/wrp-score:v_$TAG_VERSION
    depends_on:
      - npm_build
trigger:
  event:
    - promote
      
volumes:
  - name: docker-socket
    host:
      path: /var/run/docker.sock
